# https://codewithhugo.com/docker-compose-local-https/
version: '3.6'

volumes:
  postgres_data:
  bundle:
  node_modules:
  rails_cache:
  public:
  redis:

networks:
  life-net:
    name: life_network

services:
  db:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: life_db
    volumes:
      - ../docker/db/certs/server.crt:/var/lib/postgresql/server.crt
      - ../docker/db/certs/server.key:/var/lib/postgresql/server.key
      - postgres_data:/var/lib/postgresql/data
    networks:
      - life-net

  app:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile.slim.dev
    image: life:dev
    command: /bin/bash /app/boot-app.sh
    env_file:
        - ".env"
    working_dir: /app
    depends_on:
      - db
      - webpacker
      - redis
    links:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ..:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - public:/app/public/packs
    tmpfs:
      - /tmp
    networks:
      - life-net
  webpacker:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile.slim.dev
    container_name: life_webpacker
    image: life:dev
    command: /bin/bash /app/boot-webpack.sh
    volumes:
      - ..:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - public:/app/public/packs
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACK_MEASURE=false
    ports:
      - "3035:3035"
    networks:
      - life-net
  
  redis:
    container_name: life_redis
    env_file:
      - ".env"
    image: "redis:6.2.6-bullseye"
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    networks:
      - life-net
  
  # sidekiq:
  #   container_name: sidekiq
  #   command: "sidekiq -C config/sidekiq.yml"
  #   depends_on:
  #     - 'db'
  #     - 'redis'
  #   build: .
  #   volumes:
  #     - '.:/app'
  #   env_file:
  #     - '.env'
  #   networks:
  #     - life-net

  cable:
    container_name: life_cable
    depends_on:
      - 'redis'
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    networks:
      - life-net