default: &default
  adapter: "redis"
  url: <%= ENV.fetch("REDIS_URL") %>

development:
  <<: *default
  channel_prefix: "life_development"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "life_production"
